### ISSUE TITLE
Support stylelint16

### ISSUE THREAD

**Issue by newives** [stylelint-scss/stylelint-config-standard-scss#145]
Support stylelint16 https://stylelint.io/migration-guide/to-16/

**Comment by donalmurtagh** [comment]
I tried upgrading to stylelint v16.0.1 while using v11.1.0 of this package and got the following error when I ran stylelint on the command line

```
TypeError: Cannot read properties of undefined (reading 'rejected')
    at Object.<anonymous> (/home/my-app/node_modules/stylelint-scss/src/rules/comment-no-empty/index.js:12:42)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/my-app/node_modules/stylelint-scss/src/rules/index.js:31:23)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

**Comment by FloEdelmann** [comment]
Blocked by

* https://github.com/stylelint-scss/stylelint-scss/issues/894
* https://github.com/stylelint-scss/stylelint-config-recommended-scss/issues/264

**Comment by kristerkari** [comment]
New release out: https://github.com/stylelint-scss/stylelint-config-standard-scss/releases/tag/v12.0.0

**Comment by toFrankie** [comment]
👀

**Comment by Dunos** [comment]
We upgraded to both v12 of this package and stylelint to v16.1.0 but still getting the reported error (at least on Win envs). Am I the only one?

**Comment by ShaikIbrahim1** [comment]
TypeError: Cannot read properties of undefined (reading 'rejected') error - while updating angular v15 to 16.Need help.Thanks!

**Comment by szulcus** [comment]
Bump

**Comment by isuke01** [comment]
any idea?

**Comment by devfservant** [comment]
> TypeError: Cannot read properties of undefined (reading 'rejected')
at Object.

I had the same issue when upgrading stylelint to v16, but it was a package-lock.json issue.
I completely regenerated it and the problem's gone.

Not sure that there is any issue with stylelint, if it can help
