### ISSUE TITLE
Cannot resolve custom syntax module "postcss-scss"

### ISSUE THREAD

**Issue by spaceninja** [stylelint-scss/stylelint-config-standard-scss#2]
I upgraded my Stylelint plugin to use Stylelint 14 and switched from stylelint-scss to stylelint-config-standard-scss, but now all the tests for my plugin failed with the following warning.

If I remove stylelint-config-standard-scss then everything works, but I would like to continue supporting sass files in my plugin.

Any ideas how I can resolve this?

```
Cannot resolve custom syntax module "postcss-scss". Check that module "postcss-scss" is available and spelled correctly.

at getCustomSyntax (node_modules/stylelint/lib/getPostcssResult.js:97:10)
at getPostcssResult (node_modules/stylelint/lib/getPostcssResult.js:41:5)
at lintSource (node_modules/stylelint/lib/lintSource.js:76:20)
at Function.standalone [as lint] (node_modules/stylelint/lib/standalone.js:132:26)
```

**Comment by monsieurnebo** [comment]
Same issue over here.

**Comment by KyorCode** [comment]
Still having "When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option" after getting everything to the latest version.
