### ISSUE TITLE
Error: Could not find "stylelint-config-standard-scss". Do you need a `configBasedir`?

### ISSUE THREAD

**Issue by mutschelknauss** [stylelint-scss/stylelint-config-standard-scss#7]
Hi there,

When migrating to stylelint V14 and moving from standard to standard-scss everything is going smooth running stylelint locally by running: `yarn stylelint "**/*.scss"`. I get the proper errors as expected.

Only when running the new V14 update as a part of our Github Actions Super-linter setup, the errors aren't shown properly. Instead of a description what the missing linting rule is I get a reference error (at places that an linting-error is actually occuring, just not the correct error message). 

I get for example:
```
2021-11-15 23:59:20 [INFO]   ----------------------------------------------
2021-11-15 23:59:20 [INFO]   Linting [CSS] files...
2021-11-15 23:59:20 [INFO]   ----------------------------------------------
2021-11-15 23:59:20 [INFO]   ----------------------------------------------
2021-11-15 23:59:20 [INFO]   ---------------------------
2021-11-15 23:59:20 [INFO]   File:[/github/workspace/rinus-frontend/components/MetaMenu/MetaMenu.scss]
2021-11-15 23:59:21 [ERROR]   Found errors in [stylelint] linter!
2021-11-15 23:59:21 [ERROR]   Error code: 78. Command output:
------
Error: Could not find "stylelint-config-standard-scss". Do you need a `configBasedir`?
    at module.exports (/node_modules/stylelint/lib/utils/configurationError.js:10:14)
    at getModulePath (/node_modules/stylelint/lib/utils/getModulePath.js:27:9)
    at loadExtendedConfig (/node_modules/stylelint/lib/augmentConfig.js:190:21)
    at /node_modules/stylelint/lib/augmentConfig.js:167:11
```

I can imagine this is something to do with stylelint, super-linter or a typo in our configuration that isn't migrated correctly that I missed, but thought to check here first as 'configBasedir' seemed to be a common stylelint issue in the past and stylelint-config-standard-scss is the new addition compared to our stylelint V13 that was working previously in github actions.

Example of the package.json

```
{
  "name": "Demo name",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "stylelint": "stylelint \"**/*.scss\""
  },
  "devDependencies": {
    "postcss": "^8.3.11",
    "sass": "^1.42.1",
    "stylelint": "^14.1.0",
    "stylelint-config-standard-scss": "^2.0.1",
    "stylelint-order": "^5.0.0"
  }
}

```

Example of our .stylelintrc.json in /.github/linters/stylelintrc.json:

```
{
  "extends": "stylelint-config-standard-scss",
  "plugins": [
    "stylelint-order"
  ],
  "rules": {
    "selector-class-pattern": "^(((is|has|not){1}-[a-z]+)|([A-Z]{1}[a-z]+)+\\-{0,2}([a-z]+[A-Z]?[a-z]*){0,2}?((\\-[a-z]+[A-Z]?[a-z]*)?(\\-{2})([a-z]+[A-Z]?[a-z]*)*)?)$",
    "alpha-value-notation": "number",
    "at-rule-empty-line-before": null,
    "at-rule-no-unknown": null,
    "color-function-notation": "legacy",
    "color-hex-case": "upper",
    "color-hex-length": "long",
    "comment-no-empty": null,
    "function-comma-space-after": null,
    "keyframes-name-pattern": null,
    "max-line-length": null,
    "no-descending-specificity": null,
    "number-leading-zero": "never",
    "number-max-precision":null,
    "property-no-vendor-prefix": null,
    "selector-no-vendor-prefix": null,
    "string-quotes": "single",
    "value-no-vendor-prefix": null,
    "scss/at-function-pattern": null,
    "scss/at-if-no-null": null,
    "scss/at-rule-conditional-no-parentheses": null,
    "scss/at-rule-no-unknown": true,
    "scss/comment-no-empty": null,
    "scss/dollar-variable-pattern": null,
    "scss/double-slash-comment-empty-line-before": null,
    "scss/double-slash-comment-whitespace-inside": null,
    "scss/no-global-function-names": null,
    "scss/operator-no-unspaced": null,
    "order/properties-order": [
      "position",
      "z-index",
      ...etc..
      "will-change"
    ]
  }
}
```

Any idea's if this could have to do with the "stylelint-config-standard-scss" package?

**Comment by stof** [comment]
super-linter uses its own stylelint setup, not the one from your project.

**Comment by Xmetalfanx** [comment]
currently troubleshooting my local setup but I am seeing the same message as in the title of this issue, and issues are not being shown in vscode's "problem" tab for me ... it seems to have started since the stylelint 14.x upgrade ... I may revert things and go back to 13.x and see if that fixes it for me

**Comment by mutschelknauss** [comment]
Not sure if this was the cause but trying again today and updating my packages to:
```
"stylelint": "^14.2.0",
"stylelint-config-standard": "^24.0.0",
"stylelint-order": "^5.0.0",
"stylelint-scss": "^4.1.0",
"stylelint-config-standard-scss": "^3.0.0",
```

Stopped github giving me the error. 

Thanks for looking into this though!
